### ISSUE TITLE
The calc_aerodynamic_data function in Aerodynamic_surfase class must be broken into parts

### ISSUE THREAD

**Issue by CassianoMontibeller** [CeuAzul/ADR#168]
This function has no test

**Comment by rafaellehmkuhl** [comment]
Could you describe the problem and in which parts could we brake the function?

**Comment by rafaellehmkuhl** [comment]
We should think about how to transport this to ADR 2.0.

**Comment by rafaellehmkuhl** [comment]
The content of this issue is being registered in a list of things to be aware of during the development of ADR2 and the issue is being closed.
