### ISSUE TITLE
HS.py needs to be refactored

### ISSUE THREAD

**Issue by joaofoes** [CeuAzul/ADR#179]
- calc_area() function should be refactored for a functional function;
- set_incidence_range() function should be refactored for a functional function;

**Comment by rafaellehmkuhl** [comment]
update_alpha() also needs to be refactored

**Comment by rafaellehmkuhl** [comment]
We should think about how to transport this to ADR 2.0.

**Comment by rafaellehmkuhl** [comment]
The content of this issue is being registered in a list of things to be aware of during the development of ADR2 and the issue is being closed.
