### ISSUE TITLE
Function set_alpha_range in the plane class has no test and needs code improvement

### ISSUE THREAD

**Issue by CassianoMontibeller** [CeuAzul/ADR#196]

**Comment by rafaellehmkuhl** [comment]
Could you elaborate on the code improvement it needs?

**Comment by CassianoMontibeller** [comment]
Yes, I will try to do

**Comment by CassianoMontibeller** [comment]
The function set_alpha_range is badly written, it has a dependency with the Flight Stability class, which needs to be linked first

**Comment by rafaellehmkuhl** [comment]
Is it the set_alpha_range or the set_alpha_trimmed?
