### ISSUE TITLE
Static margin is fucking crazy as fuck

### ISSUE THREAD

**Issue by rafaellehmkuhl** [CeuAzul/ADR#27]
@davidssand please post the static margin crazy plots here

**Comment by davidssand** [comment]
![image](https://user-images.githubusercontent.com/42397193/52581214-506aa980-2e11-11e9-976c-f56adfc2a4d3.png)
Static margin still not plotting well. Should be constant, around 0,14.

**Comment by rafaellehmkuhl** [comment]
![image](https://user-images.githubusercontent.com/6551040/52806581-7f328b00-3070-11e9-923f-3e776e968b5b.png)
 UUUUUUUUUUUUUUUUUUUUUUUUUUUU NIIIIIIIIIIIIIIIIIIIIIIIIIIIICEEEE

Problem whas using CM instead of dCM/dAlpha on the static margin calculation.

**Comment by rafaellehmkuhl** [comment]
Biplane is also beautiful and matches EESC values (from presentation: 0-50%)

![image](https://user-images.githubusercontent.com/6551040/52806644-ae48fc80-3070-11e9-9126-f8aa03684b91.png)

**Comment by rafaellehmkuhl** [comment]
For reference, this is the CM_alpha for the biplane (Micro2018 dimensions and wings separated by 60cm):

![image](https://user-images.githubusercontent.com/6551040/52806726-e2bcb880-3070-11e9-9a02-c7a5bf038916.png)
